ALTER TABLE financial_ratios ADD COLUMN revenue_cagr_5yr REAL;
ALTER TABLE financial_ratios ADD COLUMN revenue_cagr_5yr_flag TEXT;
ALTER TABLE financial_ratios ADD COLUMN pat_cagr_5yr REAL;
ALTER TABLE financial_ratios ADD COLUMN pat_cagr_5yr_flag TEXT;
ALTER TABLE financial_ratios ADD COLUMN eps_cagr_5yr REAL;
ALTER TABLE financial_ratios ADD COLUMN eps_cagr_5yr_flag TEXT;
ALTER TABLE financial_ratios ADD COLUMN composite_quality_score REAL;
ALTER TABLE financial_ratios ADD COLUMN icr_label TEXT;
ALTER TABLE financial_ratios ADD COLUMN high_leverage_flag INTEGER;